# Generated by Django 5.2.9 on 2025-12-03 18:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("target_count", models.IntegerField(default=1)),
                ("xp_reward", models.IntegerField(default=50)),
                (
                    "quest_type",
                    models.CharField(
                        choices=[
                            ("complete_lines", "Complete Lines"),
                            ("fix_blunders", "Fix Blunders"),
                            ("perfect_streak", "Perfect Streak"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="xp",
            new_name="total_xp",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_moves_remaining",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_stamina_reset",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="times_completed",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="MoveLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_square", models.CharField(max_length=2)),
                ("target_square", models.CharField(max_length=2)),
                ("is_correct", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trainer.variation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserMistake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fen", models.CharField(max_length=100)),
                ("wrong_move", models.CharField(max_length=10)),
                ("correct_move", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mistakes",
                        to="trainer.userprofile",
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mistakes",
                        to="trainer.variation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserQuestProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("assigned_date", models.DateField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quests",
                        to="trainer.userprofile",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainer.dailyquest",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "quest", "assigned_date")},
            },
        ),
        migrations.CreateModel(
            name="UserSRSProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "next_review_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("interval", models.FloatField(default=1.0)),
                ("streak", models.IntegerField(default=0)),
                ("ease_factor", models.FloatField(default=2.5)),
                ("last_reviewed", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="srs_progress",
                        to="trainer.userprofile",
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="srs_data",
                        to="trainer.variation",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "variation")},
            },
        ),
    ]
