# Generated by Django 5.1.6 on 2025-12-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0002_dailyquest_rename_xp_userprofile_total_xp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("elite", "Elite"),
                ],
                default="intermediate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="variation",
            name="themes",
            field=models.JSONField(
                default=list,
                help_text="List of strategic themes, e.g., ['IQP', 'pawn_storm']",
            ),
        ),
        migrations.AddField(
            model_name="variation",
            name="training_goal",
            field=models.CharField(
                choices=[
                    ("tactics", "Tactics"),
                    ("strategy", "Strategy"),
                    ("attack", "Attack"),
                    ("defense", "Defense"),
                    ("endgame", "Endgame"),
                ],
                default="strategy",
                max_length=20,
            ),
        ),
    ]
