# Generated by Django 6.0 on 2025-12-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0006_userrepertoireopening"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="one_move_best_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="one_move_current_streak",
            field=models.IntegerField(default=0),
        ),
    ]
