# Generated by Django 6.0 on 2025-12-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0007_userprofile_one_move_best_streak_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="plan_interval",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
