# Generated by Django 5.2.9 on 2025-12-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0008_userprofile_current_period_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
