# Generated by Django 5.1.6 on 2025-12-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0009_userprofile_cancel_at_period_end_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "permissions": [
                    (
                        "premium_override",
                        "Can access premium features without subscription",
                    )
                ]
            },
        ),
    ]
